llm_prompts/5_how_to_use_few_shot_prompt.ipynb
- add another example few shot prompts for language translation.
=> added another example of few-shot prompt

README.md, function-calling/README.md
- added and modified comments in the respective READMEs
=> Minor comment mods in respective READMEs.

requirements.txt
- fixed requirements.txt 
- corrected the python-dotenv package
=> replaced dotenv to python-dotenv

assistants/1_how_use_assistant_tool_retriever.ipynb
- refactored code for simplification
- added repeatable steps 
- use only a single document
=> Refactored code and added repeatable steps for query the mini RAG

assistants/1_how_use_assistant_tool_retriever.ipynb, assistants/assistant_utils.py
- refactored the notebook
- added a utils file
=> Refactored the notebook; added utils files

assistants/4_how_to_use_parallel_function_calling.ipynb
-fixed a bug in formatting response to submit_tools
=> Fixed a bug in formating

assistants/5_how_to_use_code_interpreter.ipynb, function-calling/1_how_to_generate_openai_func_arguments.ipynb, function-calling/2_how_to_generate_anyscale_endpoints_func_arguments.ipynb, function-calling/world_map_llm_func_openai_with_cities.html, function-calling/world_map_nb_func_anyscale_with_cities.html, function-calling/world_map_nb_openai_func_with_cities.html
- add anyscale endpoint function calling example
- minor modes to function-calling notebooks
-
=> add function calling for anyscale endpoint example

function-calling/1_how_to_generate_openai_func_arguments.ipynb, function-calling/2_how_to_generate_anyscale_endpoints_func_arguments.ipynb, function-calling/world_map_nb_func_anyscale_with_cities.html
- added anyscale function argument generation examples
=> added anyscale function argument generation examples

llm-prompts/5_how_to_use_few_shot_prompt.ipynb, llm-prompts/7_how_to_use_react_prompt.ipynb
- Added ReAct example prompt notebook,
- modified some code and fixed nit picks
=> Added ReAct example prompt nb and modified some code

llm-prompts/7_how_to_use_react_prompt.ipynb
- added a fourth example for ReAct
=> added a fourth example for ReAct

README.md
=> Added banner for stars

function-calling/3_how_to_use_openai_anyscale_parallel_function_calling_db.ipynb, function-calling/openai_anyscale_parallel_function_calling_db.py
- renamed a file;
-  tested on anyscale endpoints mistral model
- tested .py on anyscale endpoints mistral model
=> renamed a file; tested on anyscale endpoints mistral model

function-calling/openai_anyscale_parallel_function_calling_db.py, function-calling/streamlit_func_calling_db_app.py
- added a streamlit app to query SQLite using function calling
- modified a python version of the script too
=> added a streamlit app to query SQLite using function calling

function-calling/openai_anyscale_parallel_function_calling_db.py
- fixed a bug to return an entire response, not just content from function
=> fixed a bug to return an entire response, not just content from function

function-calling/.streamlit/config.toml, llm-prompts/README.md
- Added TOC for llm-prompts readme
=> Added TOC for llm-prompts readme

llm-prompts/8_how_to_use_code_llama_prompt.ipynb, llm-prompts/README.md
- Added TOC and links to open notebook in Goole Colab
=> Added TOC and links to open notebook in Goole Colab

function-calling/sqlite_conn_cls.py
=> add sqlite singleton cls

function-calling/README.md
- added TOC for function calling and links to colab
=> added TOC for function calling and links to colab

function-calling/customer_db_utils.py, function-calling/sqlite_conn_cls.py
- added SQLite singleton class 
-  refactored some db utils code to use it
=> added SQLite singleton class and refactored some db utils code to use it

function-calling/customer_db_utils.py, function-calling/openai_anyscale_parallel_function_calling_db.py, function-calling/sqlite_conn_cls.py
- deprecated decorator
- use SQLite singleton where needed
=> deprecated decorator, use SQLlite singleton where needed

function-calling/sqlite_conn_cls.py, llm-prompts/6_how_to_use_chain_of_thought_prompt.ipynb, llm-prompts/README.md
- added colab links to readme
- fixed minor typo
- refactored some code in sqlite
=> added colab links to readme; fixed minor typos; refactored some code in sql

function-calling/3_how_to_use_openai_anyscale_parallel_function_calling_db.ipynb
-   made the reference link more explicit
=> made the reference link more explicit

function-calling/openai_parallel_function_calling_external.py
=> fixed weather unit bug

function-calling/1_how_to_generate_openai_func_arguments.ipynb, function-calling/2_how_to_generate_anyscale_endpoints_func_arguments.ipynb, function-calling/3_how_to_use_openai_anyscale_parallel_function_calling_db.ipynb, llm-prompts/1_how_to_use_basic_prompt.ipynb, llm-prompts/2_how_to_conduct_common_nlp_llm_tasks.ipynb, llm-prompts/4_how_to_use_zero_shot_prompt.ipynb, llm-prompts/5_how_to_use_few_shot_prompt.ipynb, llm-prompts/6_how_to_use_chain_of_thought_prompt.ipynb, llm-prompts/7_how_to_use_react_prompt.ipynb, llm-prompts/8_how_to_use_code_llama_prompt.ipynb
- Added note for respective .env files needed
=> Added note for respective .env files needed

llm-prompts/2_how_to_conduct_common_nlp_llm_tasks.ipynb
=> fixed a broken link

assistants/1_how_to_use_assistant_tool_retriever_part_1.ipynb, assistants/2_how_to_use_assistant_tool_retriever_part_2.ipynb, assistants/3_how_to_use_assistant_tool_retriever_part_3.ipynb, assistants/4_how_to_use_parallel_function_calling.ipynb, assistants/5_how_to_use_code_interpreter.ipynb, assistants/6_how_to_use_function_calling_tool.ipynb, assistants/7_how_to_use_function_calling_tool_google_search.ipynb
- add and mention attribution links
=> add and mention attribution links

assistants/1_how_to_use_assistant_tool_retriever_part_1.ipynb, assistants/2_how_to_use_assistant_tool_retriever_part_2.ipynb, assistants/3_how_to_use_assistant_tool_retriever_part_3.ipynb, assistants/4_how_to_use_parallel_function_calling.ipynb, assistants/5_how_to_use_code_interpreter.ipynb
- fixed minor typos and usage in comments
=> fixed minor typos and usage in comments

llm-prompts/9_how_to_use_basic_prompt_anthropic.ipynb
- fixed minor typos and print model names
=> fixed minor typos and print model names

embeddings-and-vectordbs/cosine_similarity_openai_embeddings.py
- added openai embeddings examples
=> added openai embeddings examples

chatbots/ollama_ex.py, llm-prompts/llm_clnt_factory_api.py, rags/README.md
- added ollama to client factory
- added rags/REAME (WIP)
-  tested ollama with mistral locally
=> added ollama to client factory; tested ollama with mistral locally

chatbots/ollama_ex.py, rags/README.md
- added content to README
- modified ollama example
=> added content to README; modified ollama example

rags/README.md
- corrected and reformatted references & resources
=> corrected and reformatted references & resources

rags/README.md
- added another RAG code example
=> added another RAG code example

README.md
- Added blog links based on GenAI cookbook
=> Added blog links based on GenAI cookbook

dspy/README.md
- Added DSPy directory and README, WIP
=> Added DSPy directory and README, WIP

dspy/01_basic_inline_dspy_signature_example.py, dspy/02_basic_class_dspy_signature_example.py, dspy/basic_dspy_example.py
- added simple in-line and class signatures examples
=> added simple in-line and class signatures examples

dspy/01_basic_inline_dspy_signature_example.py
- Added q&a inline signature example
=> Added q&a inline signature example

dspy/01_basic_inline_dspy_signature_example.py, dspy/02_basic_class_dspy_signature_example.py, dspy/03_dspy_nlp_tasks.py, dspy/README.md
- added dspy_utils,py
- added nlp tasks example using dspy modules
- modified README
=> added dspy_utils,py and nlp tasks using dspy modules

dspy/03_dspy_nlp_tasks.py, dspy/dspy_utils.py
- added JSON generating NLP task
- added related dspy module class
- parse command line args to specify which NLP task to run
- extended the output max tokens for OLlama to 2500
=> added JSON generating NLP task and related dspy module class

dspy/README.md
- Added toc for py code examples and links to the .py files
=> Added toc for py code examples and links to the .py files

dspy/README.md
- Minor edits correcting typos and links
=> Minor edits correcting typos and links

dspy/03_dspy_nlp_tasks.py, dspy/04_common_nlp_llm_tasks_dspy.ipynb, dspy/README.md
- Added wip notebook for NLP tasks using DSpy signature and modules
=> Added wip notebook for NLP tasks using DSpy signature and modules

dspy/03_dspy_nlp_tasks.py, dspy/04_common_nlp_llm_tasks_dspy.ipynb, dspy/README.md, dspy/dspy_utils.py
- added couple of more NLP tasks
- math word problem tasks
- updated the README file
=> added couple of more NLP tasks

dspy/03_dspy_nlp_tasks.py, dspy/04_common_nlp_llm_tasks_dspy.ipynb, dspy/dspy_utils.py
- modified the signature for SimpleAndComplexReasoning for output
=> modified the signature for SimpleAndComplexReasoning for output

dspy/07_dspy_program_of_thought.py, dspy/README.md, dspy/dspy_utils.py
- added new module ProgramOfThought for python code gen tasks
=> added new module ProgramOfThought for python code gen tasks

dspy/08_dspy_program_of_thought.ipynb, dspy/09_dspy_naive_rag.py, dspy/12_dspy_react_task.ipynb, dspy/dspy_utils.py
- minor edits, changes, and fixes
=> minor edits, changes, and fixes

README.md
=> Added DSPy blog link

llm-prompts/llm_clnt_factory_api.py
- added another Gemini vision example notebook
=> added another Gemini vision example notebook

llm-prompts/README.md
- added links to vision model notebook
=> added links to vision model notebook

llm-prompts/gemini_json.ipynb
As an example, segments texts into topics
=> Extract JSON using prompt engineering

README.md
- added more comments and fixed some typos
=> added more comments and fixed some typos

README.md
- Added more descriptions for chapters
=> Added more descriptions for chapters

README.md
- added more introductory remarks
=> added more introductory remarks

requirements.txt
=> Update requirements.txt - fix pineclone to pinecone

assistants/function_utils.py, assistants/google_search_utils.py, fine-tuning/explore_hf_data.py, function-calling/openai_anyscale_parallel_function_calling_db.py, function-calling/openai_parallel_function_calling_external.py, function-calling/streamlit_func_calling_db_app.py, llm-prompts/basic_ollama_llama3.py
- try & test Llama3-7b on Olama on the laptop
=> try Llama3-7b on Olama on the laptop

README.md
minor editing and formatting fixes
=> minor editing and formatting fixes

dspy/README.md
=> Corrected some links
